
from openmdao.main.api import Assembly, VariableTree
from openmdao.lib.datatypes.api import Instance, VarTree, Str

class CaseInputsBase(VariableTree):

    case_name = Str(desc='Name of the case to run')

class CaseOutputsBase(VariableTree):

    case_name = Str(desc='Name of the case to run')

class FUSEDAssembly(Assembly):
    """
    Base class for all FUSED-Wind assemblies which extends OpenMDAO's Assembly
    with dedicated slots for I/O and methods for recording runs.
    """

    inputs = VarTree(CaseInputsBase(), iotype='in', desc='Placeholder for FUSED-Wind inputs to a simulation code')
    outputs = VarTree(CaseOutputsBase(), iotype='out', desc='Placeholder for FUSED-Wind outputs generated by a'
                                          'simulation code')
